In [1]:
import numpy as np
new_matrix = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]]) 

print (new_matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
import numpy as np

# defining polynomial function
var = np.poly1d([13, 0, 0, -1])
print("Polynomial function, f(x):\n", var)
  
# calculating the derivative
derivative = var.deriv()
print("Derivative, f(x)'=", derivative)
  
# calculates the derivative of after 
# given value of x
print("When x=5  f(x)'=", derivative(5))

Polynomial function, f(x):
    3
3 x - 1
Derivative, f(x)'=    2
9 x
When x=5  f(x)'= 225
